from __future__ import annotations

import pytest

from upool.cursor import parse as parser
from upool.cursor.models import COOKIE_NAME, COOKIE_NAMES

# Shaped like the real thing: a WorkOS user id, and a JWT whose alphabet is
# base64url - no colons, no percent signs, nothing the parser could split on.
USER_A = "user_01JQ8ZK3M4N5P6Q7R8S9T0V1W2"
USER_B = "user_01HXY9M2B4C6D8E0F2G4H6J8K1"
USER_CAROL = "user_01CA2R3O4L5M6N7P8Q9R0S1T2"
USER_DAVE = "user_01DA4V5E6F7G8H9J0K1L2M3N4"
USER_EVE = "user_01EV6E7F8G9H0J1K2L3M4N5P6"
TOKEN_A = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxSlE4WksifQ.9pQvL3xRt7"
TOKEN_B = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxSFhZOU0yIn0.4kMwT7bFc2"

ENCODED_A = f"{USER_A}%3A%3A{TOKEN_A}"
ENCODED_B = f"{USER_B}%3A%3A{TOKEN_B}"


def netscape(domain: str, name: str, value: str, secure: str = "FALSE") -> str:
    """One ``cookies.txt`` row. Built rather than pasted, because a literal tab
    in a source file is invisible and one turned into spaces by an editor would
    silently stop testing this form at all."""
    return "\t".join([domain, "TRUE", "/", secure, "1786000000", name, value])


COOKIES_TXT = "\n".join(
    [
        "# Netscape HTTP Cookie File",
        "# https://curl.se/docs/http-cookies.html",
        "# This file was generated by libcurl! Edit at your own risk.",
        "",
        netscape(".google.com", "NID", "511=q8Vd7nKcHs2wRt"),
        netscape("#HttpOnly_.github.com", "_gh_sess", "tJx9AbQ%2FmN4", secure="TRUE"),
        netscape("#HttpOnly_.cursor.com", COOKIE_NAME, ENCODED_A, secure="TRUE"),
        netscape(".stripe.com", "__stripe_mid", "9f2b41c8-6de0-4a1b"),
    ]
)


def only(result: parser.ParseResult) -> parser.ParsedAccount:
    assert len(result.accounts) == 1, result.accounts
    return result.accounts[0]


# ------------------------------------------------------------------ cookies.txt


def test_a_netscape_row_is_read_from_its_name_and_value_fields():
    account = only(parser.parse(netscape(".cursor.com", COOKIE_NAME, ENCODED_A)))
    assert account.user_id == USER_A
    assert account.token == TOKEN_A


def test_a_browser_export_finds_the_one_cursor_cookie_among_the_noise():
    """Three other domains and a comment header, reported only as a number.

    This is the paste the silent-skip rule exists for: naming each rejected line
    would put six failures in a toast that has one thing to say.
    """
    result = parser.parse(COOKIES_TXT)
    assert only(result).user_id == USER_A
    assert result.skipped == 6


def test_an_httponly_row_is_a_record_and_not_a_comment():
    """The session cookie is HttpOnly, so every real export writes it with a
    leading ``#``. Reading the ``#`` before counting the tabs would throw away
    the only line in the file that mattered."""
    line = netscape("#HttpOnly_.cursor.com", COOKIE_NAME, ENCODED_A, secure="TRUE")
    assert only(parser.parse(line)).token == TOKEN_A


def test_a_row_for_another_cookie_on_cursors_own_domain_is_skipped():
    result = parser.parse(netscape(".cursor.com", "NEXT_LOCALE", "en"))
    assert result.accounts == []
    assert result.skipped == 1


# --------------------------------------------------------------- cookie strings


def test_a_cookie_assignment_stands_on_its_own():
    account = only(parser.parse(f"{COOKIE_NAME}={ENCODED_A}"))
    assert (account.user_id, account.token) == (USER_A, TOKEN_A)


@pytest.mark.parametrize("name", COOKIE_NAMES)
def test_every_name_cursor_still_answers_is_recognised(name):
    assert only(parser.parse(f"{name}={ENCODED_A}")).token == TOKEN_A


def test_the_name_is_matched_however_it_was_typed():
    assert only(parser.parse(f"{COOKIE_NAME.lower()}={ENCODED_A}")).token == TOKEN_A


def test_a_whole_cookie_header_finds_the_session_among_the_others():
    header = (
        f"Cookie: intercom-id-9f2b=41c8-6de0-4a1b; {COOKIE_NAME}={ENCODED_A}; "
        "NEXT_LOCALE=en; _dd_s=rum=0&expire=1786000000"
    )
    assert only(parser.parse(header)).token == TOKEN_A


def test_a_set_cookie_response_line_is_read_past_its_attributes():
    line = f"Set-Cookie: {COOKIE_NAME}={ENCODED_A}; Path=/; Secure; HttpOnly; SameSite=Lax"
    assert only(parser.parse(line)).token == TOKEN_A


# ----------------------------------------------------------------------- bare


def test_a_bare_credential_is_taken_encoded_or_not():
    encoded = only(parser.parse(ENCODED_A))
    plain = only(parser.parse(f"{USER_B}::{TOKEN_B}"))
    assert (encoded.user_id, encoded.token) == (USER_A, TOKEN_A)
    assert (plain.user_id, plain.token) == (USER_B, TOKEN_B)


def test_the_stored_token_is_the_decoded_half():
    """What is stored is what a request needs before it is re-encoded, so no
    ``%3A`` survives into the record on either side of the split."""
    account = only(parser.parse(ENCODED_A))
    assert "%3A" not in account.user_id
    assert "%3A" not in account.token
    assert account.token == TOKEN_A


def test_only_the_first_separator_splits_the_credential():
    """A second ``::`` further along belongs to the token, not to a third field.

    The two halves are an id and a credential - the credential is opaque, so
    splitting on every separator would corrupt whatever Cursor puts in it next.
    """
    token = "eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6ImE6OmIifQ::v2::e30"
    account = only(parser.parse(f"{USER_A}::{token}"))
    assert account.user_id == USER_A
    assert account.token == token


def test_a_line_of_prose_with_a_separator_in_it_is_not_a_credential():
    result = parser.parse("note:: rotated the cursor cookie on friday")
    assert result.accounts == []
    assert result.skipped == 1


# ------------------------------------------------------------------------ csv


def test_a_csv_row_carries_the_email_beside_the_cookie():
    account = only(parser.parse(f"ada@example.com,{ENCODED_A}"))
    assert account.email == "ada@example.com"
    assert account.token == TOKEN_A


def test_a_csv_row_whose_token_half_has_no_user_id_is_skipped():
    """An email is not identity here.

    Without a user id the row cannot be matched against the pool, so it could
    never be refreshed or deduplicated - storing it under an invented key would
    make the next paste of the same account a second account.
    """
    result = parser.parse(f"ada@example.com,{TOKEN_A}")
    assert result.accounts == []
    assert result.skipped == 1


def test_a_csv_header_row_is_skipped_like_any_other_line():
    result = parser.parse("\n".join(["email,token", f"ada@example.com,{ENCODED_A}"]))
    assert only(result).email == "ada@example.com"
    assert result.skipped == 1


def test_a_two_column_csv_of_something_else_is_not_read_as_a_pool():
    result = parser.parse("\n".join(["claude,3.2.1", "codex,0.48.0"]))
    assert result.accounts == []
    assert result.skipped == 2


# ----------------------------------------------------------------------- json


def test_a_pretty_printed_object_is_read_before_the_lines_are():
    """Twenty lines of one record, not twenty failures - which is why the whole
    input is tried as JSON first."""
    result = parser.parse(
        "\n".join(
            [
                "{",
                '  "email": "ada@example.com",',
                '  "name": "Ada",',
                f'  "accessToken": "{ENCODED_A}"',
                "}",
            ]
        )
    )
    account = only(result)
    assert (account.user_id, account.token, account.email) == (USER_A, TOKEN_A, "ada@example.com")
    assert result.skipped == 0


def test_an_array_of_accounts_keeps_the_order_it_was_written_in():
    result = parser.parse(
        f'[{{"email": "ada@example.com", "token": "{ENCODED_A}"}},'
        f' {{"email": "bob@example.com", "token": "{USER_B}::{TOKEN_B}"}}]'
    )
    assert [account.user_id for account in result.accounts] == [USER_A, USER_B]
    assert [account.email for account in result.accounts] == [
        "ada@example.com",
        "bob@example.com",
    ]


def test_a_nested_dump_is_walked_and_the_email_above_carries_down():
    """The layout is whatever the script that wrote it chose, so the tree is
    searched rather than a known shape read - and a wrapper that names the
    account still belongs to the token nested under it."""
    result = parser.parse(
        '{"exportedAt": 1786000000, "accounts": [{"email": "ada@example.com",'
        f' "session": {{"cookie": "{COOKIE_NAME}={ENCODED_A}"}}}}]}}'
    )
    account = only(result)
    assert (account.user_id, account.token) == (USER_A, TOKEN_A)
    assert account.email == "ada@example.com"


def test_json_objects_one_per_line_are_read_line_by_line():
    result = parser.parse(
        "\n".join(
            [
                f'{{"token": "{ENCODED_A}"}}',
                f"{COOKIE_NAME}={ENCODED_B}",
            ]
        )
    )
    assert [account.user_id for account in result.accounts] == [USER_A, USER_B]
    assert result.skipped == 0


def test_an_object_holding_an_unusable_token_is_counted_as_skipped():
    result = parser.parse(f'[{{"token": "not-a-cookie"}}, {{"token": "{ENCODED_A}"}}]')
    assert only(result).user_id == USER_A
    assert result.skipped == 1


def test_json_that_holds_no_credential_at_all_is_one_skipped_record():
    result = parser.parse('{"version": 2, "accounts": []}')
    assert result.accounts == []
    assert result.skipped == 1


# --------------------------------------------------------------- counting rules


def test_an_input_that_is_entirely_junk_yields_nothing_and_says_how_much():
    result = parser.parse(
        "\n".join(
            [
                "Traceback (most recent call last):",
                '  File "switch.py", line 12, in <module>',
                "    raise SystemExit(1)",
                "SystemExit: 1",
            ]
        )
    )
    assert result.accounts == []
    assert result.skipped == 4


def test_an_empty_paste_is_empty():
    result = parser.parse("")
    assert result.accounts == []
    assert result.skipped == 0


def test_blank_lines_between_accounts_are_not_failures():
    result = parser.parse(f"\n\n{ENCODED_A}\n\n   \n{ENCODED_B}\n\n")
    assert len(result.accounts) == 2
    assert result.skipped == 0


def test_a_repeated_user_id_is_counted_once_and_the_newer_token_wins():
    """Re-pasting a rotated cookie is the common case, not a mistake, and the
    row it lands on keeps the position it already had."""
    rotated = f"{TOKEN_A}.rotated"
    result = parser.parse(
        "\n".join([ENCODED_A, f"{USER_B}::{TOKEN_B}", f"{USER_A}::{rotated}"])
    )
    assert [account.user_id for account in result.accounts] == [USER_A, USER_B]
    assert result.accounts[0].token == rotated
    assert result.skipped == 0


def test_an_email_learned_from_an_earlier_line_survives_a_later_one_without_it():
    result = parser.parse("\n".join([f"ada@example.com,{ENCODED_A}", f"{USER_A}::{TOKEN_B}"]))
    account = only(result)
    assert account.token == TOKEN_B
    assert account.email == "ada@example.com"


def test_a_mixed_paste_takes_every_form_at_once():
    """One box, four shapes, in whatever order they were collected."""
    result = parser.parse(
        "\n".join(
            [
                "# pasted from three machines",
                netscape("#HttpOnly_.cursor.com", COOKIE_NAME, ENCODED_A, secure="TRUE"),
                f"{COOKIE_NAME}={USER_B}%3A%3A{TOKEN_B}",
                f"carol@example.com,{USER_CAROL}%3A%3A{TOKEN_A}",
                f"{USER_DAVE}::{TOKEN_B}",
                f'{{"email": "eve@example.com", "token": "{USER_EVE}::{TOKEN_A}"}}',
            ]
        )
    )
    assert [account.user_id for account in result.accounts] == [
        USER_A,
        USER_B,
        USER_CAROL,
        USER_DAVE,
        USER_EVE,
    ]
    assert result.skipped == 1
